#!/bin/sh

PATH=/c/Program\ Files/Git/usr/bin/:$PATH

ARCHIVE_DIRECTORY_NAME=Qt5.4.1-x86-msvc2012_opengl
echo \$ARCHIVE_DIRECTORY_NAME: $ARCHIVE_DIRECTORY_NAME
mkdir -p "$ARCHIVE_DIRECTORY_NAME"

tar czvf "$ARCHIVE_DIRECTORY_NAME".tar.gz "$ARCHIVE_DIRECTORY_NAME"
/c/Program\ Files/7-Zip/7z a -tzip -mx9 "$ARCHIVE_DIRECTORY_NAME".zip -r "$ARCHIVE_DIRECTORY_NAME"/*
/c/Program\ Files/7-Zip/7z a -t7z -mx9 "$ARCHIVE_DIRECTORY_NAME".7z -r "$ARCHIVE_DIRECTORY_NAME"/*

ARCHIVE_DEBUG_DIRECTORY_NAME=Qt5.4.1-x86-msvc2012_opengl_debug
echo \$ARCHIVE_DEBUG_DIRECTORY_NAME: $ARCHIVE_DEBUG_DIRECTORY_NAME
mkdir -p "$ARCHIVE_DEBUG_DIRECTORY_NAME"

tar czvf "$ARCHIVE_DEBUG_DIRECTORY_NAME".tar.gz "$ARCHIVE_DEBUG_DIRECTORY_NAME"
/c/Program\ Files/7-Zip/7z a -tzip -mx9 "$ARCHIVE_DEBUG_DIRECTORY_NAME".zip -r "$ARCHIVE_DEBUG_DIRECTORY_NAME"/*
/c/Program\ Files/7-Zip/7z a -t7z -mx9 "$ARCHIVE_DEBUG_DIRECTORY_NAME".7z -r "$ARCHIVE_DEBUG_DIRECTORY_NAME"/*

ARCHIVE_RELEASE_DIRECTORY_NAME=Qt5.4.1-x86-msvc2012_opengl_release
echo \$ARCHIVE_RELEASE_DIRECTORY_NAME: $ARCHIVE_RELEASE_DIRECTORY_NAME
mkdir -p "$ARCHIVE_RELEASE_DIRECTORY_NAME"

tar czvf "$ARCHIVE_RELEASE_DIRECTORY_NAME".tar.gz "$ARCHIVE_RELEASE_DIRECTORY_NAME"
/c/Program\ Files/7-Zip/7z a -tzip -mx9 "$ARCHIVE_RELEASE_DIRECTORY_NAME".zip -r "$ARCHIVE_RELEASE_DIRECTORY_NAME"/*
/c/Program\ Files/7-Zip/7z a -t7z -mx9 "$ARCHIVE_RELEASE_DIRECTORY_NAME".7z -r "$ARCHIVE_RELEASE_DIRECTORY_NAME"/*