#!/bin/sh

PATH=/c/Program\ Files/Git/usr/bin/:$PATH

if [[ $JOB_NAME =~ "vc11" ]]
then
 VC_NAME="vc11" #msvs2012
 QT_PATH=/c/Qt/Qt5.4.1-x86-msvc2012_opengl/5.4/msvc2012_opengl
elif [[ $JOB_NAME =~ "vc12" ]]
then
 VC_NAME="vc12" #msvs2013
 QT_PATH=/c/Qt/Qt5.4.1-x86-msvc2013_opengl/5.4/msvc2013_opengl
else
 exit 42
fi

ARCHIVE_DIRECTORY_NAME=qt5.4.1-x86-"$VC_NAME"_b"$BUILD_NUMBER"
echo \$ARCHIVE_DIRECTORY_NAME: $ARCHIVE_DIRECTORY_NAME
mkdir -p "$ARCHIVE_DIRECTORY_NAME"

cp -pv $QT_PATH/bin/{Qt5Cored.dll,Qt5Core.dll} $ARCHIVE_DIRECTORY_NAME
cp -pv $QT_PATH/bin/{Qt5Guid.dll,Qt5Gui.dll} $ARCHIVE_DIRECTORY_NAME
cp -pv $QT_PATH/bin/{Qt5Widgetsd.dll,Qt5Widgets.dll} $ARCHIVE_DIRECTORY_NAME
cp -pv $QT_PATH/bin/{Qt5Networkd.dll,Qt5Network.dll} $ARCHIVE_DIRECTORY_NAME
cp -pv $QT_PATH/bin/{Qt5Qmld.dll,Qt5Qml.dll} $ARCHIVE_DIRECTORY_NAME
cp -pv $QT_PATH/bin/{Qt5Quickd.dll,Qt5Quick.dll} $ARCHIVE_DIRECTORY_NAME
cp -pv $QT_PATH/bin/{Qt5Xmld.dll,Qt5Xml.dll} $ARCHIVE_DIRECTORY_NAME
cp -pv $QT_PATH/bin/icudt*.dll $ARCHIVE_DIRECTORY_NAME
cp -pv $QT_PATH/bin/icuin*.dll $ARCHIVE_DIRECTORY_NAME
cp -pv $QT_PATH/bin/icuuc*.dll $ARCHIVE_DIRECTORY_NAME
cp -prv $QT_PATH/plugins/platforms $ARCHIVE_DIRECTORY_NAME/platforms
cp -prv $QT_PATH/qml/QtQml $ARCHIVE_DIRECTORY_NAME/QtQml
cp -prv $QT_PATH/qml/QtQuick $ARCHIVE_DIRECTORY_NAME/QtQuick
cp -prv $QT_PATH/qml/QtQuick.2 $ARCHIVE_DIRECTORY_NAME/QtQuick.2

tar czvf "$ARCHIVE_DIRECTORY_NAME".tar.gz "$ARCHIVE_DIRECTORY_NAME"
/c/Program\ Files/7-Zip/7z a -tzip -mx9 "$ARCHIVE_DIRECTORY_NAME".zip -r "$ARCHIVE_DIRECTORY_NAME"/*
/c/Program\ Files/7-Zip/7z a -t7z -mx9 "$ARCHIVE_DIRECTORY_NAME".7z -r "$ARCHIVE_DIRECTORY_NAME"/*

ARCHIVE_DEBUG_DIRECTORY_NAME=qt5.4.1-x86-"$VC_NAME"_b"$BUILD_NUMBER"-debug
echo \$ARCHIVE_DEBUG_DIRECTORY_NAME: $ARCHIVE_DEBUG_DIRECTORY_NAME
mkdir -p "$ARCHIVE_DEBUG_DIRECTORY_NAME"

cp -pv $QT_PATH/bin/Qt5Cored.dll $ARCHIVE_DEBUG_DIRECTORY_NAME
cp -pv $QT_PATH/bin/Qt5Guid.dll $ARCHIVE_DEBUG_DIRECTORY_NAME
cp -pv $QT_PATH/bin/Qt5Widgetsd.dll $ARCHIVE_DEBUG_DIRECTORY_NAME
cp -pv $QT_PATH/bin/Qt5Networkd.dll $ARCHIVE_DEBUG_DIRECTORY_NAME
cp -pv $QT_PATH/bin/Qt5Qmld.dll $ARCHIVE_DEBUG_DIRECTORY_NAME
cp -pv $QT_PATH/bin/Qt5Quickd.dll $ARCHIVE_DEBUG_DIRECTORY_NAME
cp -pv $QT_PATH/bin/Qt5Xmld.dll $ARCHIVE_DEBUG_DIRECTORY_NAME
cp -pv $QT_PATH/bin/icudt*.dll $ARCHIVE_DEBUG_DIRECTORY_NAME
cp -pv $QT_PATH/bin/icuin*.dll $ARCHIVE_DEBUG_DIRECTORY_NAME
cp -pv $QT_PATH/bin/icuuc*.dll $ARCHIVE_DEBUG_DIRECTORY_NAME
cp -prv $QT_PATH/plugins/platforms $ARCHIVE_DEBUG_DIRECTORY_NAME/platforms
cp -prv $QT_PATH/qml/QtQml $ARCHIVE_DEBUG_DIRECTORY_NAME/QtQml
cp -prv $QT_PATH/qml/QtQuick $ARCHIVE_DEBUG_DIRECTORY_NAME/QtQuick
cp -prv $QT_PATH/qml/QtQuick.2 $ARCHIVE_DEBUG_DIRECTORY_NAME/QtQuick.2

tar czvf "$ARCHIVE_DEBUG_DIRECTORY_NAME".tar.gz "$ARCHIVE_DEBUG_DIRECTORY_NAME"
/c/Program\ Files/7-Zip/7z a -tzip -mx9 "$ARCHIVE_DEBUG_DIRECTORY_NAME".zip -r "$ARCHIVE_DEBUG_DIRECTORY_NAME"/*
/c/Program\ Files/7-Zip/7z a -t7z -mx9 "$ARCHIVE_DEBUG_DIRECTORY_NAME".7z -r "$ARCHIVE_DEBUG_DIRECTORY_NAME"/*

ARCHIVE_RELEASE_DIRECTORY_NAME=qt5.4.1-x86-"$VC_NAME"_b"$BUILD_NUMBER"-release
echo \$ARCHIVE_RELEASE_DIRECTORY_NAME: $ARCHIVE_RELEASE_DIRECTORY_NAME
mkdir -p "$ARCHIVE_RELEASE_DIRECTORY_NAME"


cp -pv $QT_PATH/bin/Qt5Core.dll $ARCHIVE_RELEASE_DIRECTORY_NAME
cp -pv $QT_PATH/bin/Qt5Gui.dll $ARCHIVE_RELEASE_DIRECTORY_NAME
cp -pv $QT_PATH/bin/Qt5Widgets.dll $ARCHIVE_RELEASE_DIRECTORY_NAME
cp -pv $QT_PATH/bin/Qt5Network.dll $ARCHIVE_RELEASE_DIRECTORY_NAME
cp -pv $QT_PATH/bin/Qt5Qml.dll $ARCHIVE_RELEASE_DIRECTORY_NAME
cp -pv $QT_PATH/bin/Qt5Quick.dll $ARCHIVE_RELEASE_DIRECTORY_NAME
cp -pv $QT_PATH/bin/Qt5Xml.dll $ARCHIVE_RELEASE_DIRECTORY_NAME
cp -pv $QT_PATH/bin/icudt*.dll $ARCHIVE_RELEASE_DIRECTORY_NAME
cp -pv $QT_PATH/bin/icuin*.dll $ARCHIVE_RELEASE_DIRECTORY_NAME
cp -pv $QT_PATH/bin/icuuc*.dll $ARCHIVE_RELEASE_DIRECTORY_NAME
cp -prv $QT_PATH/plugins/platforms $ARCHIVE_RELEASE_DIRECTORY_NAME/platforms
cp -prv $QT_PATH/qml/QtQml $ARCHIVE_RELEASE_DIRECTORY_NAME/QtQml
cp -prv $QT_PATH/qml/QtQuick $ARCHIVE_RELEASE_DIRECTORY_NAME/QtQuick
cp -prv $QT_PATH/qml/QtQuick.2 $ARCHIVE_RELEASE_DIRECTORY_NAME/QtQuick.2

tar czvf "$ARCHIVE_RELEASE_DIRECTORY_NAME".tar.gz "$ARCHIVE_RELEASE_DIRECTORY_NAME"
/c/Program\ Files/7-Zip/7z a -tzip -mx9 "$ARCHIVE_RELEASE_DIRECTORY_NAME".zip -r "$ARCHIVE_RELEASE_DIRECTORY_NAME"/*
/c/Program\ Files/7-Zip/7z a -t7z -mx9 "$ARCHIVE_RELEASE_DIRECTORY_NAME".7z -r "$ARCHIVE_RELEASE_DIRECTORY_NAME"/*