#!/bin/sh

PATH=/c/Program\ Files/Git/usr/bin/:$PATH

if [[ $JOB_NAME =~ "vc11" ]]
then
 VC_NAME="msvs2012_vc11"
elif [[ $JOB_NAME =~ "vc12" ]]
then
 VC_NAME="msvs2013_vc12"
else
 VC_NAME="vc"
fi

ARCHIVE_DIRECTORY_NAME=qt5.4.1-x86-"$VC_NAME"
echo \$ARCHIVE_DIRECTORY_NAME: $ARCHIVE_DIRECTORY_NAME
mkdir -p "$ARCHIVE_DIRECTORY_NAME"

tar czvf "$ARCHIVE_DIRECTORY_NAME".tar.gz "$ARCHIVE_DIRECTORY_NAME"
/c/Program\ Files/7-Zip/7z a -tzip -mx9 "$ARCHIVE_DIRECTORY_NAME".zip -r "$ARCHIVE_DIRECTORY_NAME"/*
/c/Program\ Files/7-Zip/7z a -t7z -mx9 "$ARCHIVE_DIRECTORY_NAME".7z -r "$ARCHIVE_DIRECTORY_NAME"/*

ARCHIVE_DEBUG_DIRECTORY_NAME=qt5.4.1-x86-"$VC_NAME"-debug
echo \$ARCHIVE_DEBUG_DIRECTORY_NAME: $ARCHIVE_DEBUG_DIRECTORY_NAME
mkdir -p "$ARCHIVE_DEBUG_DIRECTORY_NAME"

tar czvf "$ARCHIVE_DEBUG_DIRECTORY_NAME".tar.gz "$ARCHIVE_DEBUG_DIRECTORY_NAME"
/c/Program\ Files/7-Zip/7z a -tzip -mx9 "$ARCHIVE_DEBUG_DIRECTORY_NAME".zip -r "$ARCHIVE_DEBUG_DIRECTORY_NAME"/*
/c/Program\ Files/7-Zip/7z a -t7z -mx9 "$ARCHIVE_DEBUG_DIRECTORY_NAME".7z -r "$ARCHIVE_DEBUG_DIRECTORY_NAME"/*

ARCHIVE_RELEASE_DIRECTORY_NAME=qt5.4.1-x86-"$VC_NAME"-release
echo \$ARCHIVE_RELEASE_DIRECTORY_NAME: $ARCHIVE_RELEASE_DIRECTORY_NAME
mkdir -p "$ARCHIVE_RELEASE_DIRECTORY_NAME"

tar czvf "$ARCHIVE_RELEASE_DIRECTORY_NAME".tar.gz "$ARCHIVE_RELEASE_DIRECTORY_NAME"
/c/Program\ Files/7-Zip/7z a -tzip -mx9 "$ARCHIVE_RELEASE_DIRECTORY_NAME".zip -r "$ARCHIVE_RELEASE_DIRECTORY_NAME"/*
/c/Program\ Files/7-Zip/7z a -t7z -mx9 "$ARCHIVE_RELEASE_DIRECTORY_NAME".7z -r "$ARCHIVE_RELEASE_DIRECTORY_NAME"/*